### ISSUE TITLE
Fetching products by category_slug or category_id not working

### ISSUE THREAD

**Issue by Rishab1207** [chec/commerce.js#142]
Whenever I'm fetching the products by `category_slug` or `category_id` in next js then it's throwing an error.

This is the code that I've written 

```js
export const getStaticProps = async ({ params }) => {
	const { slug } = params;
	console.log(slug);
	const products = await commerce.products.list({ category_slug: slug });
	console.log(products);
	return {
		props: {
			products,
		},
	};
};
```

The error that I'm getting

```js
{
  message: 'Unsuccessful response (422: Unprocessable Entity) received',
  statusCode: 422,
  statusText: 'Unprocessable Entity',
  data: {
    status_code: 422,
    error: {
      message: 'The given data was invalid.',
      type: 'unprocessable_entity',
      errors: [Object]
    }
  },
  originalError: Error: Request failed with status code 422
      at createError (E:\Web Development\Projects\Main Projects\startup\frontend\node_modules\axios\lib\core\createError.js:16:15)
      at settle (E:\Web Development\Projects\Main Projects\startup\frontend\node_modules\axios\lib\core\settle.js:17:12)
      at IncomingMessage.handleStreamEnd (E:\Web Development\Projects\Main Projects\startup\frontend\node_modules\axios\lib\adapters\http.js:260:11)
      at IncomingMessage.emit (events.js:214:15)
      at endReadableNT (_stream_readable.js:1178:12)
      at processTicksAndRejections (internal/process/task_queues.js:77:11) {
    config: {
      url: 'products',
      method: 'get',
      data: null,
      headers: [Object],
      params: [Object],
      baseURL: 'https://api.chec.io/v1/',
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 60000,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus]
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'GET /v1/products?category_slug=potrait HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'X-Authorization: <My Public Key>\r\n' +
        'X-Chec-Agent: commerce.js/v2\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Host: api.chec.io\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      path: '/v1/products?category_slug=potrait',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      _redirectable: [Writable],
      [Symbol(kNeedDrain)]: false,
      [Symbol(isCorked)]: false,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    response: {
      status: 422,
      statusText: 'Unprocessable Entity',
      headers: [Object],
      config: [Object],
      request: [ClientRequest],
      data: [Object]
    },
    isAxiosError: true,
    toJSON: [Function: toJSON]
  }
}
```

**Comment by robbieaverill** [comment]
Hi @Rishab1207, in your response you have this:
```
  data: {
    status_code: 422,
    error: {
      message: 'The given data was invalid.',
      type: 'unprocessable_entity',
      errors: [Object]
    }
  },
```

If you look at the `errors: [Object]` part of that response it will tell you what your problem is.

At a guess, I would say that the error says that `category_slug` must be an array, and your request should look like this:

```
const products = await commerce.products.list({ category_slug: [slug] });
```

You can see which version of the Chec API your request was handled by by inspecting the `Chec-Version` header in the `response.headers` object in your snippet above. You can change the version either in the Chec Dashboard > API keys section, or by specifying a version in the `Chec-Version` request header. See our [API docs](https://commercejs.com/docs/api/#versioning) for notes around breaking changes - specifically 2021-03-03 for this issue.

Happy building!
